services:
  goapp:
    container_name: goapp
    image: goapp:1.0.0
    build:
      context: ./backend
      dockerfile: go.dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres # This line was changed from 'postgres' to 'db'
    ports:
      - "5432:5432"
    volumes:
      - "pgdata:/var/lib/postgresql/data"

volumes:
  pgdata: {}
